Repository harness/harness-core-ui, pull requests merged in 2022-09, with the labels that each got.

#10327 fix: [PIE-4642]: google artifact registry added
  src/modules/10-common/featureFlags.ts
  src/modules/10-common/strings/strings.en.yaml
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactConnector.module.scss
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactConnector.module.scss.d.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactImagePathTagView.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/GoogleArtifactRegistry.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/__tests__/GoogleArtifactRegistry.test.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/__tests__/__snapshots__/GoogleArtifactRegistry.test.tsx.snap
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/70-pipeline/utils/stageHelpers.ts
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/GoogleArtifactRegistrySource.tsx
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/__tests__/GoogleArtifactsRegistrySource.test.tsx
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/__tests__/__snapshots__/GoogleArtifactsRegistrySource.test.tsx.snap
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/__tests__/mock.ts
  src/modules/75-cd/factory/ArtifactSourceFactory/ArtifactSourceBaseFactory.tsx
  src/services/cd-ng/index.tsx
  src/stringTypes.ts
Labels: DO NOT MERGE

#10174 fix: [PIE-4585]: Custom artifact source
  src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
  src/modules/10-common/components/ShellScriptMonaco/ShellScriptMonaco.module.scss
  src/modules/10-common/components/ShellScriptMonaco/ShellScriptMonaco.tsx
  src/modules/10-common/strings/strings.en.yaml
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactConnector.module.scss
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactConnector.module.scss.d.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/CustomArtifact.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/__tests__/CustomArtifact.test.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/__tests__/__snapshots__/CustomArtifact.test.tsx.snap
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactWizard/ArtifactWizard.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
  src/modules/70-pipeline/components/PipelineSteps/Steps/Steps.module.scss
  src/modules/70-pipeline/components/PipelineSteps/Steps/Steps.module.scss.d.ts
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/CustomArtifactSource/CustomArtifactSource.tsx
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/CustomArtifactSource/__tests__/__snapshots__/CustomArtifactSource.test.tsx.snap
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/CustomArtifactSource/__tests__/mocks.ts
  src/stringTypes.ts
Labels: DO NOT MERGE

#10961 feat: [PIE-5000]: Azure Repos Webhook Trigger Refactor
  src/modules/72-triggers/components/Triggers/TriggerInterface.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/AzureRepo/AzureRepo.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/context/PipelineTriggersContext.tsx
  src/modules/72-triggers/factory/TriggerFactory.tsx
Labels: tech_debt

#11139 feat: [CCM-8092]: Added types for CCM MFE
  src/microfrontends/ChildAppMounter.tsx
  src/microfrontends/index.ts
  src/microfrontends/package.json
  src/modules/20-rbac/components/RBACTooltip/RBACTooltip.tsx
  src/modules/75-ce/RouteDestinations.tsx
  src/modules/75-ce/components/AnomaliesFilter/AnomaliesFilter.tsx
  src/modules/75-ce/interface/CCMUIApp.types.ts
Labels: DO NOT MERGE

#10320 fix: [PIE-4641]: github package registry artifact added
  src/modules/10-common/featureFlags.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GithubPackageRegistry/GithubPackageRegistry.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GithubPackageRegistry/__tests__/GithubPackageRegistry.test.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GithubPackageRegistry/__tests__/__snapshots__/GithubPackageRegistry.test.tsx.snap
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/GoogleArtifactRegistry.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/70-pipeline/components/PipelineStudio/ExecutionStrategy/Phases.tsx
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GithubPackageRegistrySource/GithubPackageRegistrySource.tsx
  src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/artifactSourceUtils.ts
  src/services/cd-ng/index.tsx
  src/stringTypes.ts
Labels: DO NOT MERGE

#11054 feat: [CDS-42429]: customDeployment support in services
  src/modules/10-common/interfaces/RouteInterfaces.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
  src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesHelper.ts
  src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
  src/modules/70-pipeline/components/PipelineSteps/PipelineStepInterface.ts
  src/modules/70-pipeline/utils/stageHelpers.ts
  src/modules/70-pipeline/utils/templateUtils.ts
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpec.module.scss
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpec.module.scss.d.ts
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpec.tsx
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpecEditable.tsx
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpecInputSetMode.tsx
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpecInterface.ts
  src/modules/75-cd/components/PipelineSteps/CustomDeploymentServiceSpec/CustomDeploymentServiceSpecVariablesForm.tsx
  src/modules/75-cd/components/PipelineSteps/PipelineStepsUtil.ts
  src/modules/75-cd/components/PipelineSteps/SshWinRmAwsInfrastructureSpec/SshWinRmAwsInfrastructureSpec.tsx
  src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/__tests__/SshWinRmAzureInfrastructureSpec.test.tsx
  src/modules/75-cd/components/PipelineSteps/index.ts
  src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraDefinition/DeployInfraDefinition.tsx
  src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceDefinition/DeployServiceDefinition.tsx
  src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.module.scss
  src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.module.scss.d.ts
  src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
  src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/DeploymentInfraWrapper/DeploymentInfraUtils.tsx
  src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/Constants.ts
  src/modules/75-cd/utils/deploymentUtils.ts
  src/services/cd-ng/index.tsx
  src/services/pipeline-ng/index.tsx
  src/services/template-ng/index.tsx
Labels: DO NOT MERGE

#10966 fix: [CDS-41809] : Fixed Runtime values for helm chart getting empty in PipelineInput step of triggers
  src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
  src/modules/72-triggers/pages/triggers/views/modals/SelectArtifactModal.tsx
Labels: bug

#11517 fix: [PIE-5579]: removed empty scss files commited
  src/modules/72-triggers/components/steps/ArtifactTriggerConditionsPanel/ArtifactConditionsPanel.module.scss
  src/modules/72-triggers/components/steps/ArtifactTriggerInputPanel/ArtifactTriggerInputPanel.module.scss
Labels: bug
