Repository harness/harness-core-ui, pull requests merged in 2022-08, with the labels that each got.

#10507 fix: [PIE-4790] : Fixed "What would you like to deploy?" broken UI issue on High resolution
  src/modules/75-cd/components/PipelineStudio/DeployStage/EditStageView/EditStageView.tsx
  src/modules/75-cd/components/PipelineStudio/DeployStage/EditStageView/__test__/__snapshots__/EditStageView.test.tsx.snap
Labels: bug

#10456 feat: [Chaos-151]: ChaosDelegate creation using connectors (UI)
  src/microfrontends/package.json
  src/modules/75-chaos/RouteDestinations.tsx
  src/modules/75-chaos/interfaces/Chaos.types.ts
Labels: enhancement

#10526 fix: [CDS-41683]: changed path to extend support for initial values in env V2 runtime
  src/modules/70-pipeline/components/PipelineInputSetForm/StageInputSetForm.tsx
Labels: Testing

#10439 fix: [PIE-4746]: input set values retaining on yaml visual switch
  src/modules/70-pipeline/components/InputSetForm/FormikInputSetForm.tsx
Labels: DO NOT MERGE, Testing

#10363 feat: [PIE-4566]: Triggers Refactor - I
  src/modules/10-common/featureFlags.ts
  src/modules/10-common/interfaces/RouteInterfaces.ts
  src/modules/72-triggers/RouteDestinations.tsx
  src/modules/72-triggers/components/AddConditionsSection/AddConditionRow.tsx
  src/modules/72-triggers/components/AddConditionsSection/AddConditions.module.scss
  src/modules/72-triggers/components/AddConditionsSection/AddConditions.module.scss.d.ts
  src/modules/72-triggers/components/AddConditionsSection/AddConditionsSection.tsx
  src/modules/72-triggers/components/ConnectorSection/ConnectorSection.tsx
  src/modules/72-triggers/components/TabWizard/TabWizard.module.scss
  src/modules/72-triggers/components/TabWizard/TabWizard.module.scss.d.ts
  src/modules/72-triggers/components/TabWizard/TabWizard.tsx
  src/modules/72-triggers/components/TabWizard/TabWizardFooter/TabWizardFooter.module.scss
  src/modules/72-triggers/components/TabWizard/TabWizardFooter/TabWizardFooter.module.scss.d.ts
  src/modules/72-triggers/components/TabWizard/TabWizardFooter/TabWizardFooter.tsx
  src/modules/72-triggers/components/TabWizard/TabWizardHeader/TabWizardHeader.module.scss
  src/modules/72-triggers/components/TabWizard/TabWizardHeader/TabWizardHeader.module.scss.d.ts
  src/modules/72-triggers/components/TabWizard/TabWizardHeader/TabWizardHeader.tsx
  src/modules/72-triggers/components/TabWizard/TabWizardUtils.tsx
  src/modules/72-triggers/components/TabWizard/context/TabWizardContext.tsx
  src/modules/72-triggers/components/TriggerDetails/TriggerBreadcrumbs/TriggerBreadcrumbs.tsx
  src/modules/72-triggers/components/TriggerDetails/TriggerDetails.module.scss
  src/modules/72-triggers/components/TriggerDetails/TriggerDetails.module.scss.d.ts
  src/modules/72-triggers/components/TriggerDetails/TriggerDetails.tsx
  src/modules/72-triggers/components/TriggerDetails/TriggerToolbar/TriggerToolbar.tsx
  src/modules/72-triggers/components/Triggers/Trigger.tsx
  src/modules/72-triggers/components/Triggers/TriggerInterface.tsx
  src/modules/72-triggers/components/Triggers/TriggerWidget.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/Github/Github.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/WebhookTrigger.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/WebhookTriggerWizard.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/WizardInterface.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/components/TitleWithSwitch/TitleWithSwitch.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/context/PipelineTriggersContext.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/utils.tsx
  src/modules/72-triggers/components/Triggers/utils.tsx
  src/modules/72-triggers/components/pages/TriggersWizardPage/TriggersWizardPage.tsx
  src/modules/72-triggers/components/steps/WebhookConditionsPanel/WebhookConditionsPanel.module.scss
  src/modules/72-triggers/components/steps/WebhookConditionsPanel/WebhookConditionsPanel.module.scss.d.ts
  src/modules/72-triggers/components/steps/WebhookConditionsPanel/WebhookConditionsPanel.tsx
  src/modules/72-triggers/components/steps/WebhookPipelineInputPanel/WebhookPipelineInputPanel.module.scss
  src/modules/72-triggers/components/steps/WebhookPipelineInputPanel/WebhookPipelineInputPanel.module.scss.d.ts
  src/modules/72-triggers/components/steps/WebhookPipelineInputPanel/WebhookPipelineInputPanel.tsx
  src/modules/72-triggers/components/steps/WebhookTriggerConfigPanel/WebhookTriggerConfigPanel.module.scss
  src/modules/72-triggers/components/steps/WebhookTriggerConfigPanel/WebhookTriggerConfigPanel.module.scss.d.ts
  src/modules/72-triggers/components/steps/WebhookTriggerConfigPanel/WebhookTriggerConfigPanel.tsx
  src/modules/72-triggers/components/steps/utils.tsx
  src/modules/72-triggers/factory/AbstractTriggerFactory.tsx
  src/modules/72-triggers/factory/TriggerFactory.tsx
Labels: tech_debt

#10657 feat: [PL-27391]: Adding Custom SM support in secret flow
  cypress/fixtures/pipeline/api/connector/connectorCatalogue.json
  package.json
  src/modules/10-common/components/ScriptVariableRuntimeInput/ScriptVariablesRuntimeInput.module.scss
  src/modules/10-common/components/ScriptVariableRuntimeInput/ScriptVariablesRuntimeInput.module.scss.d.ts
  src/modules/10-common/components/ScriptVariableRuntimeInput/ScriptVariablesRuntimeInput.tsx
  src/modules/10-common/strings/strings.en.yaml
  src/modules/10-common/utils/Validation.tsx
  src/modules/30-secrets/components/CreateUpdateSecret/CreateUpdateSecret.tsx
  src/modules/30-secrets/components/CreateUpdateSecret/__tests__/CreateUpdateSecretForCustomSecretManager.test.tsx
  src/modules/30-secrets/components/CreateUpdateSecret/__tests__/customSMSecretMocks.ts
  src/modules/30-secrets/components/CreateUpdateSecret/views/CustomFormFields/CustomFormFields.module.scss
  src/modules/30-secrets/components/CreateUpdateSecret/views/CustomFormFields/CustomFormFields.module.scss.d.ts
  src/modules/30-secrets/components/CreateUpdateSecret/views/CustomFormFields/CustomFormFields.tsx
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/CreateCustomSMConnector.tsx
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/__tests__/CreateCustomSMConnector.test.tsx
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/__tests__/CustomSMConfigStep.test.tsx
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/__tests__/__snapshots__/CreateCustomSMConnector.test.tsx.snap
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/__tests__/__snapshots__/CustomSMConfigStep.test.tsx.snap
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/__tests__/mock.ts
  src/modules/35-connectors/components/CreateConnector/CustomSecretManagerConnector/views/CustomSMConfigStep.tsx
  src/modules/35-connectors/components/CreateConnector/__test__/commonMock.ts
  src/modules/35-connectors/components/CreateConnectorWizard/CreateConnectorWizard.tsx
  src/modules/35-connectors/constants.ts
  src/modules/35-connectors/interfaces/ConnectorInterface.ts
  src/modules/35-connectors/modals/ConnectorModal/useCreateConnectorModal.tsx
  src/modules/35-connectors/pages/connectors/ConnectorsPage.tsx
  src/modules/35-connectors/pages/connectors/utils/ConnectorHelper.tsx
  src/modules/35-connectors/pages/connectors/utils/ConnectorListViewUtils.tsx
  src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
  src/modules/35-connectors/pages/connectors/views/savedDetailsView/SavedConnectorDetails.tsx
  src/modules/35-connectors/strings/strings.en.yaml
  src/services/cd-ng/index.tsx
  src/services/cv/index.tsx
  src/stringTypes.ts
  yarn.lock
Labels: DO NOT MERGE
