Repository harness/harness-core-ui, pull requests merged in 2022-06, with the labels that each got.

#9076 feat: [CCM-7646]: Implemented sorting, searching and filtering for AS rules and savings data
  src/modules/75-ce/common/TimeRangePicker/TimeRangePicker.module.scss
  src/modules/75-ce/common/TimeRangePicker/TimeRangePicker.module.scss.d.ts
  src/modules/75-ce/common/TimeRangePicker/TimeRangePicker.tsx
  src/modules/75-ce/common/TimeRangePicker/__tests__/TimeRangePicker.test.tsx
  src/modules/75-ce/common/hooks/__tests__/useAllQueryParamsState.test.tsx
  src/modules/75-ce/common/hooks/useAllQueryParamsState.tsx
  src/modules/75-ce/components/AnomaliesFilter/AnomaliesFilter.tsx
  src/modules/75-ce/components/COGatewayList/COGatewayCumulativeAnalytics.module.scss
  src/modules/75-ce/components/COGatewayList/COGatewayCumulativeAnalytics.module.scss.d.ts
  src/modules/75-ce/components/COGatewayList/COGatewayCumulativeAnalytics.tsx
  src/modules/75-ce/components/COGatewayList/COGatewayList.module.scss
  src/modules/75-ce/components/COGatewayList/COGatewayList.module.scss.d.ts
  src/modules/75-ce/components/COGatewayList/COGatewayList.tsx
  src/modules/75-ce/components/COGatewayList/GatewayListFilters.tsx
  src/modules/75-ce/components/COGatewayList/SavingsPieChart.tsx
  src/modules/75-ce/components/COGatewayList/SpendVsSavingsChart.tsx
  src/modules/75-ce/components/COGatewayList/Utils.tsx
  src/modules/75-ce/components/COGatewayList/__tests__/COGatewayCumulativeAnalytics.test.tsx
  src/modules/75-ce/components/COGatewayList/__tests__/COGatewayList.test.tsx
  src/modules/75-ce/components/COGatewayList/__tests__/GatewayListFilters.test.tsx
  src/modules/75-ce/components/COGatewayList/__tests__/__snapshots__/COGatewayCumulativeAnalytics.test.tsx.snap
  src/modules/75-ce/components/COGatewayList/__tests__/__snapshots__/COGatewayList.test.tsx.snap
  src/modules/75-ce/components/COGatewayList/__tests__/data.ts
  src/modules/75-ce/components/PersepectiveExplorerFilters/PerspectiveExplorerFilters.tsx
  src/modules/75-ce/constants.ts
  src/modules/75-ce/pages/node-details/NodeDetailsPage.tsx
  src/modules/75-ce/pages/overview/OverviewPage.tsx
  src/modules/75-ce/pages/workload-details/WorkloadDetailsPage.tsx
  src/modules/75-ce/strings/strings.en.yaml
  src/modules/75-ce/utils/momentUtils.ts
  src/services/lw/index.tsx
  src/services/lw/swagger.json
  src/stringTypes.ts
Labels: WIP

#9413 feat: [CDS-37779]: added 'open in new tab' option for services list
  src/modules/75-cd/components/Services/ServicesList/ServiceList.module.scss
  src/modules/75-cd/components/Services/ServicesList/ServiceList.module.scss.d.ts
  src/modules/75-cd/components/Services/ServicesList/ServicesList.tsx
Labels: in-progress

#9708 feat: [CI-4539]: enable CI step groups behind feature flag
  src/modules/10-common/featureFlags.ts
  src/modules/75-ci/components/PipelineStudio/BuildStageSetupShell/BuildStageSetupShell.tsx
Labels: DO NOT MERGE
