Repository harness/harness-core-ui, pull requests merged in 2023-01, with the labels that each got.

#13240 fix: [PIE-7345]: extra stage data populating on selective re-run of pipeline
  src/modules/70-pipeline/components/RunPipelineModal/__tests__/useInputSets.test.tsx
  src/modules/70-pipeline/components/RunPipelineModal/useInputSets.tsx
Labels: DO NOT MERGE

#12902 fix: [CI-6350]: "run in debug mode" execution action for CI pipelines
  src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
  src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
  src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
  src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListTable.tsx
  src/modules/70-pipeline/pages/execution-list/__tests__/ExecutionList.test.tsx
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionHeader/ExecutionHeader.tsx
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionLandingPage.tsx
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/__tests__/ExecutionLandingPage.test.tsx
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/75-cd/pages/pipeline-deployment-list/__tests__/CDPipelineDeploymentList.test.tsx
  src/modules/75-cf/pages/pipeline-deployment-list/__tests__/CFPipelineDeploymentList.test.tsx
  src/modules/75-ci/pages/pipeline-deployment-list/__tests__/CIPipelineDeploymentList.test.tsx
  src/services/pipeline-ng/index.tsx
  src/stringTypes.ts
Labels: in-progress

#12197 fix: [CDS-45912]: nexus3 + ami trigger v2 added
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/72-triggers/components/Triggers/ArtifactTrigger/AmazonMachineImage/AmazonMachineImage.ts
  src/modules/72-triggers/components/Triggers/ArtifactTrigger/TriggersWizardPageUtils.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactHelper.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactInterface.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/AmazonMachineImage.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/NexusArtifact/NexusArtifact.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactUtils.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/72-triggers/factory/TriggerFactory.tsx
  src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
  src/stringTypes.ts
Labels: DO NOT MERGE

#13198 feat: [CDS-49406]: ADFS Support for ServiceNow Authentication
  src/modules/10-common/featureFlags.ts
  src/modules/35-connectors/common/ConnectorTestConnection/ConnectorTestConnection.tsx
  src/modules/35-connectors/components/CreateConnector/ServiceNowConnector/ServiceNowConnector.module.scss
  src/modules/35-connectors/components/CreateConnector/ServiceNowConnector/ServiceNowConnector.module.scss.d.ts
  src/modules/35-connectors/components/CreateConnector/ServiceNowConnector/ServiceNowDetailsForm.tsx
  src/modules/35-connectors/components/CreateConnector/ServiceNowConnector/__test__/__snapshots__/ServiceNowConnector.test.tsx.snap
  src/modules/35-connectors/pages/connectors/utils/ConnectorHelper.tsx
  src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
  src/modules/35-connectors/strings/strings.en.yaml
  src/stringTypes.ts
Labels: PR Testing
