Repository harness/harness-core-ui, pull requests merged in 2023-07, with the labels that each got.

#15941 feat: [CDS-69167]: Multi Region Artifact Trigger
  cypress/integration/72-triggers/ArtifactTrigger/ArtifactTriggerConfig.ts
  cypress/integration/72-triggers/ArtifactTrigger/artifact-trigger-helpers/defineArtifactSource.ts
  cypress/integration/72-triggers/ArtifactTrigger/artifact-trigger-helpers/fillArtifactConnectorDataAndMoveToNextStep.ts
  cypress/integration/72-triggers/ArtifactTrigger/artifact-trigger-helpers/fillArtifactWizardData.ts
  cypress/integration/72-triggers/constants.ts
  cypress/integration/72-triggers/triggers-helpers/visitTriggersPage.ts
  src/modules/10-common/featureFlags.ts
  src/modules/10-common/interfaces/RouteInterfaces.ts
  src/modules/70-pipeline/RouteDestinations.tsx
  src/modules/70-pipeline/strings/strings.en.yaml
  src/modules/72-triggers/components/Triggers/ArtifactTrigger/ArtifactTrigger.tsx
  src/modules/72-triggers/components/Triggers/ArtifactTrigger/ArtifactTriggerWizard.tsx
  src/modules/72-triggers/components/Triggers/ArtifactTrigger/TriggersWizardPageUtils.ts
  src/modules/72-triggers/components/Triggers/ManifestTrigger/ManifestTrigger.tsx
  src/modules/72-triggers/components/Triggers/ManifestTrigger/ManifestTriggerWizard.tsx
  src/modules/72-triggers/components/Triggers/ScheduledTrigger/Cron/Cron.tsx
  src/modules/72-triggers/components/Triggers/ScheduledTrigger/ScheduledTrigger.tsx
  src/modules/72-triggers/components/Triggers/ScheduledTrigger/ScheduledTriggerWizard.tsx
  src/modules/72-triggers/components/Triggers/ScheduledTrigger/utils.tsx
  src/modules/72-triggers/components/Triggers/Trigger.tsx
  src/modules/72-triggers/components/Triggers/TriggerInterface.tsx
  src/modules/72-triggers/components/Triggers/TriggerWidget.tsx
  src/modules/72-triggers/components/Triggers/TriggerWizardInterface.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/AzureRepo/AzureRepo.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/Bitbucket/Bitbucket.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/Github/Github.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/Gitlab/Gitlab.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/WebhookTrigger.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/WebhookTriggerWizard.tsx
  src/modules/72-triggers/components/Triggers/WebhookTrigger/utils.tsx
  src/modules/72-triggers/components/pages/TriggersWizardPage/TriggersWizardPage.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactInterface.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactListView/ArtifactListView.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactListView/PrimaryArtifact/PrimaryArtifactView.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactConnector.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactUtils.ts
  src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactsSelection.tsx
  src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerDetailPage/TriggerDetailPage.tsx
  src/modules/72-triggers/pages/triggers/TriggersPage.tsx
  src/modules/72-triggers/pages/triggers/TriggersWizardPage.tsx
  src/modules/72-triggers/pages/triggers/__tests__/TriggersListUtils.test.ts
  src/modules/72-triggers/pages/triggers/interface/TriggersWizardInterface.ts
  src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
  src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
  src/modules/72-triggers/pages/triggers/views/TriggersList.tsx
  src/modules/72-triggers/pages/triggers/views/TriggersListSection.tsx
  src/stringTypes.ts
Labels: cds-pl-ready-review

#16907 fix: [CDS-73422]: modified ux for pipeline exec summary
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.module.scss
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.module.scss.d.ts
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.tsx
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/__tests__/__snapshots__/ExecutionMetadata.test.tsx.snap
  src/modules/70-pipeline/pages/execution/ExecutionLandingPage/__tests__/__snapshots__/ExecutionLandingPage.test.tsx.snap
Labels: in-progress

#17031 feat: [PL-40211]: maintain formatting of chat responses
  src/modules/10-common/components/DocsChat/DocsChat.module.scss
  src/modules/10-common/components/DocsChat/DocsChat.tsx
Labels: WIP
